### ISSUE TITLE
Figure out a better way to present the features in the SpeedDial FAB

### ISSUE THREAD

**Issue by algernon** [keyboardio/chrysalis-bundle-keyboardio#78]
Thanks to @davidaue for digging up the Material Design [recommendation](https://material.io/design/components/buttons-floating-action-button.html#usage), namely: "Only use a FAB if it is the most suitable way to present a screen’s primary action."

The stuff in the speed dial does not meet that requirement. As such, we should figure out a better way to present those things. Perhaps an action bar at the bottom? A thin one? That could still go on every page globally.

**Comment by davidaue** [comment]
Maybe and overflow menu?
[Top bar Anatomy](https://material.io/design/components/app-bars-top.html#anatomy)

**Comment by algernon** [comment]
Yeah, that could work, but not all pages have an appbar right now, which is why I was thinking about a bottom action area instead.

Something like an [Expanding Bottom Sheet](https://material.io/design/components/sheets-bottom.html#expanding-bottom-sheet)? That sounds like something appropriate, and I can fit it onto all pages with ease, and it wouldn't look too out of place.

**Comment by algernon** [comment]
I think I'll be going with a menu in the lower right corner, that expands upwards.
