### ISSUE TITLE
When we're showing the "programming the keyboard" spinning progress indicator, we should disable the top-of-page blue progress indicator

### ISSUE THREAD

**Issue by obra** [keyboardio/chrysalis-bundle-keyboardio#84]

**Comment by algernon** [comment]
The top-of-page blue progress indicator is - as far as I see - unrelated. That one's shown when we're trying to query the keyboard with a `version` focus command. I guess that never finishes?

**Comment by obra** [comment]
Ah. yeah. that must be it. Maybe it needs a timeout?

**Comment by algernon** [comment]
It... should time out, eventually, after about 15 seconds. (I'll lower the timeout soon)

Can you verify that it stops the top-blue animation after about 15 seconds? And if it doesn't, is there anything on the dev console?

**Comment by obra** [comment]
It was there for multiple minutes. Unfortunately, after flashing the
firmware, I got to a white screen and couldn't enable the dev console. I'll
try to repro later today.

**Comment by algernon** [comment]
I just tried to reproduce this, with #95 applied, using `Model01-Firmware`'s master branch (thus, no `version` command), and the blue progress bar wasn't shown during flash. I couldn't even see if the bar even appeared...

**Comment by algernon** [comment]
Oooh, I managed to reproduce it. I had another app steal serial from Chrysalis, and now I have LinearProgress stuck on the top permanently.
